import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const inventoryPath = resolve(root, 'packages/app/src/generated/third-party-licenses.json');
const releaseInfoPath = resolve(root, 'packages/app/src/generated/release-info.ts');
const engineVersionPath = resolve(root, 'packages/core/src/generated/version.ts');
const targets = ['@mibbeacon/desktop', '@mibbeacon/mobile'];
const compatibleLicenses = new Set([
  '0BSD',
  'Apache 2.0',
  'Apache-2.0',
  'BSD-2-Clause',
  'BSD-3-Clause',
  'BlueOak-1.0.0',
  'CC-BY-4.0',
  'CC0-1.0',
  'ISC',
  'MIT',
  'MPL-2.0',
  'Unlicense',
  '(BSD-2-Clause OR MIT OR Apache-2.0)',
  '(BSD-3-Clause OR GPL-2.0)',
  '(MIT OR CC0-1.0)',
]);

// argparse is an Expo CLI build-time dependency and is not linked into an APK/AAB/IPA JS bundle.
const buildOnlyExceptions = new Map([['argparse', 'Expo CLI build-time tool; not bundled']]);

function packageLicenses(target) {
  const executable = process.platform === 'win32' ? 'pnpm.cmd' : 'pnpm';
  const result = spawnSync(
    executable,
    ['--filter', target, 'licenses', 'list', '--prod', '--json'],
    { cwd: root, encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 },
  );
  if (result.status !== 0) {
    throw new Error(`Could not enumerate ${target} licenses:\n${result.stderr || result.stdout}`);
  }
  return JSON.parse(result.stdout);
}

function generate() {
  const packages = new Map();
  const exceptions = [];
  for (const target of targets) {
    const groups = packageLicenses(target);
    for (const [license, entries] of Object.entries(groups)) {
      for (const entry of entries) {
        if (!compatibleLicenses.has(license)) {
          const reason = buildOnlyExceptions.get(entry.name);
          if (!reason)
            throw new Error(`Unknown or GPL-incompatible license: ${entry.name} (${license})`);
          exceptions.push({ name: entry.name, license, reason, target });
          continue;
        }
        for (const version of entry.versions) {
          const key = `${entry.name}@${version}`;
          const existing = packages.get(key);
          packages.set(key, {
            name: entry.name,
            version,
            license,
            homepage: entry.homepage ?? null,
            targets: [
              ...new Set([...(existing?.targets ?? []), target.replace('@mibbeacon/', '')]),
            ].sort(),
          });
        }
      }
    }
  }
  return {
    generatedBy: 'pnpm licenses list --prod',
    compatibleLicensePolicy: [...compatibleLicenses].sort(),
    buildOnlyExceptions: exceptions.sort((a, b) => a.name.localeCompare(b.name)),
    packages: [...packages.values()].sort((a, b) =>
      `${a.name}@${a.version}`.localeCompare(`${b.name}@${b.version}`),
    ),
  };
}

function releaseInfo() {
  const manifest = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
  const repository = manifest.repository.url.replace(/\.git$/, '');
  return `// Generated by dev/license-audit.mjs. Do not edit by hand.\nexport const RELEASE_INFO = ${JSON.stringify(
    {
      version: manifest.version,
      license: manifest.license,
      repository,
      exactSourceUrl: `${repository}/tree/v${manifest.version}`,
    },
    null,
    2,
  )} as const;\n`;
}

const inventory = `${JSON.stringify(generate(), null, 2)}\n`;
const info = releaseInfo();
const version = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8')).version;
const engineVersion = `// Generated by dev/license-audit.mjs. Do not edit by hand.\nexport const ENGINE_VERSION = ${JSON.stringify(version)};\n`;
if (process.argv.includes('--check')) {
  if (
    readFileSync(inventoryPath, 'utf8') !== inventory ||
    readFileSync(releaseInfoPath, 'utf8') !== info ||
    readFileSync(engineVersionPath, 'utf8') !== engineVersion
  ) {
    throw new Error('Generated release/license metadata is stale. Run pnpm release:prepare.');
  }
  process.stdout.write('Release metadata and dependency licenses are current and compatible.\n');
} else {
  writeFileSync(inventoryPath, inventory);
  writeFileSync(releaseInfoPath, info);
  writeFileSync(engineVersionPath, engineVersion);
  process.stdout.write('Wrote dependency inventory and release version metadata.\n');
}
