/**
 * Renderer-safe entry point. Exposes ONLY the lightweight helpers and types the
 * UI needs — never the engine implementation (createEngine → net-snmp → node
 * builtins), so the browser/renderer bundle stays free of the SNMP stack.
 * Hosts that actually run the engine import from '@mibbeacon/core' instead.
 */
export {
  EventBus,
  type EngineEvent,
  type EngineEventChannel,
  type EngineEventListener,
  type Unsubscribe,
} from './events';
export { MibBeaconError, type MibBeaconErrorCode } from './errors';
export { inferWireType, validateVarbindInput } from './snmp/wire-types';
export type { RowStatusCreateResult } from './ops/row-status';
export { decodeTableIndex } from '@mibbeacon/smi/client';
export type {
  EngineAPI,
  EngineInfo,
  GetRequest,
  SetRequest,
  WalkRequest,
  AgentTarget,
  OperationTarget,
  AgentProfileInput,
  AgentV3Input,
  AgentSecretsInput,
  AgentProfile,
  AgentCreateDraft,
  AgentUpdateDraft,
  AgentGroup,
  AgentTestResult,
  OperationHandle,
  OperationStartRequest,
  OperationStats,
  BookmarkOperation,
  OperationBookmarkInput,
  OperationBookmark,
  WalkSnapshotInput,
  WalkSnapshotSummary,
  WalkSnapshot,
  TableRowCreateRequest,
  TableRowDeleteRequest,
  TrapReceiverStatus,
  TrapQuery,
  TrapSavedFilter,
  TrapV3UserProfile,
  TrapV3UserDraft,
  TrapSendPreset,
  TrapRuleCondition,
  TrapRuleActions,
  TrapRule,
  TrapRuleDraft,
  NotificationAgentSendRequest,
  MibsAPI,
  MibStartImportRequest,
  ResolverAPI,
  ResolverOperationState,
  ResolverOperationStatus,
  ResolverConsentResponse,
  ResolverSettings,
  ResolverSourceDraft,
  ResolverSourceSecrets,
  ResolverSourceTestResult,
  ResolverSourcePreviewResult,
  ResolverOperationResult,
  ResolverCacheStats,
  OidLookupRequest,
  OidLookupResult,
  ResolverHistoryEntry,
  PollMode,
  PollSeries,
  PollSeriesDraft,
  PollSample,
  PollWatch,
  PollChart,
  DiscoveryCredential,
  DiscoveryResult,
  WalkDiffRow,
  PortViewRow,
  ToolsAPI,
} from './api/engine-api';
export type { SourceConfig, SourceKind } from '@mibbeacon/resolver';
export type {
  MibNodeKind,
  MibNodeSummary,
  MibNodeDetail,
  ModuleInfo,
  ModuleDependency,
  ModuleView,
  ModuleTreeRole,
  ModuleTreeNode,
  ImportResult,
  MibSearchHit,
  ResolvedName,
  MibTextFile,
  MibFileImportInspection,
  MibModuleCollisionKind,
  MibFileInspection,
  MibFilesInspection,
} from '@mibbeacon/smi';
export type { TableIndexDescriptor } from '@mibbeacon/smi/client';
export type {
  AgentSpec,
  V3Credentials,
  SnmpVersion,
  SecurityLevel,
  AuthProtocol,
  PrivProtocol,
  DecodedVarbind,
  SnmpWireType,
  SnmpVarbindInput,
  NotificationKind,
  NotificationPayload,
  NotificationSendRequest,
  NotificationSendResult,
} from './snmp/types';
export type { TrapRecord, TrapReceiverConfig, TrapV3User } from './snmp/receiver';
export type { PacketTraceEvent, PacketTraceServiceStatus, PacketTraceSettings } from './packet-trace';
export { createEngineProxy, type ProxyAdapter, type BridgeResult } from './proxy';
