services:
  ftp:
    build: .
    ports:
      - "2121:21"
      - "21100-21110:21100-21110"
    healthcheck:
      test: ["CMD-SHELL", "nc -z 127.0.0.1 21"]
      interval: 2s
      timeout: 1s
      retries: 15
